<?php
  $heading = get_sub_field('headings');
  $form = get_sub_field('contact_form');
  $map = get_sub_field('map_embed');
  echo ex_wrap('start', 'contact-people');
    echo '<div class="module-inner">';
      echo '<div class="contact-form">';
        echo '<h1>' . $heading['form'] . '</h1>';
        echo do_shortcode('[contact-form-7 id="' . $form . '"]');
      echo '</div>';
        echo '<div class="contact-directory">';
          echo '<h1>' . $heading['directory'] . '</h1>';
          get_template_part('modules/staff');
        echo '</div>';
    echo '</div>';
  echo ex_wrap('end');
  echo ex_wrap('start', 'contact-location');
    echo '<div class="module-inner">';
      echo '<div class="contact-data">';
        echo '<h1>' . $heading['map'] . '</h1>';
        echo '<p class="address">';
          ex_contact('address');
        echo '</p>';
        ex_contact('phone');
        ex_contact('email');
      echo '</div>';
      echo '<div class="contact-map">';
        echo $map;
      echo '</div>';
    echo '</div>';
  echo ex_wrap('end');
